# Generated by Django 2.0.1 on 2018-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.CharField(max_length=10, verbose_name='Weeks')),
            ],
        ),
    ]
